### ISSUE TITLE
😑😑

### ISSUE THREAD

**Issue by KratoSkills** [aniketstark/STARK3.0#8]
It doesn't contain a method to check if it has already downloaded the modules.zip and secretservices.zip in the previous run or not. ADD THIS.

It's algorithm to detect Termux:API, if it's present, is not correct. Always shows an error at line 37 even when I have it installed, given all permissions and in termux via apt install termux-api. KINDLY FIX THIS, because it's shit with these bugs.

With these bugs it's just exhausting our data at every run. Because it doesn't have an algorithm for, as mentioned in the first paragraph.

**Comment by aniketstark** [comment]
it been long time
error was fixed but with **unstable**
![kekwtf](https://user-images.githubusercontent.com/31062805/152632313-161f0231-f5be-4df8-be5a-7d2bf8762f77.gif)
